### PR TITLE
add `arabic` translation file

### PR DESCRIPTION
**Pull request by atefBB**

### CODE REVIEW

**Comment by joeblau** [comment]
Thank you so much!!!

**Comment by atefBB** [comment]
@joeblau Thank you. 
Is there any plan to implement `multi-language switcher` (a simple button) in the website?
I can't find the `language switcher` to see the translation in `action`.

**Comment by joeblau** [comment]
I'm sure there is.  The way I test is by switching the base language on my Mac.

**Comment by atefBB** [comment]
Nice to have a to do `things`!
Thanks.

**Pull request merged**
